export const surpriseMePrompts = [
  "A train station that leads to an alternate dimension",
  "A skyscraper made entirely out of ice cream",
  "A garden filled with oversized flowers and insects",
  "A city skyline that appears to be melting like a Dali painting",
  "A futuristic city powered by bio-luminescent plants",
  "A desert landscape with a giant, glowing moon in the background",
  "A floating island in the clouds with waterfalls cascading off the edges",
  "A castle made entirely out of crystal, with rainbow-colored walls",
  "A surreal world where everything is upside down",
  "A peaceful forest with a glowing, magical tree in the center",
  "A giant, mythical sea creature emerging from the ocean",
  "A haunted mansion with a mysterious, ghostly figure in the window",
  "A futuristic laboratory with glowing test tubes and scientific equipment",
  "An abandoned amusement park with rusted rides and overgrown vegetation",
  "A city street filled with neon lights and glowing signs",
  "A steampunk airship soaring through the clouds",
  "A cityscape with enormous, floating air balloons",
  "A fantasy world with multiple moons and a glowing, magical sky",
  "A tropical beach with crystal clear water and colorful fish",
  "A post-apocalyptic world with abandoned buildings and overgrown vegetation",
  "A space station orbiting a distant planet",
  "A deep sea world with bioluminescent creatures and glowing coral reefs",
  "A futuristic city with flying cars and advanced technology",
  "A cyberpunk city with neon lights and high-tech gadgets",
  "A world covered in ice and snow, with a massive, frozen castle",
  "A dark, mysterious forest with hidden creatures lurking in the shadows",
  "A magical castle floating in the clouds",
  "A surreal, abstract world with geometric shapes and patterns",
  "A city submerged in water, with skyscrapers towering above the waves",
  "A jungle filled with exotic plants and animals",
  "A futuristic city with towering, interconnected bridges",
  "A world made entirely out of candy and sweets",
  "A city surrounded by a glowing, magical force field",
  "A giant robot battling a giant monster in a futuristic city",
  "A peaceful countryside scene with rolling hills and grazing animals",
  "A mystical garden with statues that come to life at night",
  "A world with floating islands and a massive waterfall in the center",
  "A mysterious cave with glowing crystals and underground rivers",
  "A futuristic spaceport with spaceships taking off and landing",
  "A city built entirely out of recycled materials",
  "A desert oasis with palm trees and a sparkling pool",
  "A city skyline at night with stars and a full moon in the background",
  "A forest filled with fairies and other magical creatures",
  "A world where time moves at different speeds in different places",
  "A floating city in the clouds with a massive airship docked nearby",
  "A futuristic city with skyscrapers that stretch into space",
  "A cityscape with massive, towering trees instead of buildings",
  "A city covered in vines and foliage, with abandoned cars and buildings",
  "A world with massive, towering giants and tiny, delicate fairies",
  "A mysterious temple in the middle of the jungle, with hidden treasures inside",
];
